name: Build Sistema Biblioteca Seba Bertello

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: ðŸ“¥ Checkout repo
        uses: actions/checkout@v4

      - name: ðŸ“¦ Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ðŸ”§ Instalar dependencias
        run: npm install

      - name: ðŸ› ï¸ Compilar ejecutable
        run: npm run build

      - name: ðŸ“¤ Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: EJECUTE_ACA_SistemaBertello
          path: dist/EJECUTE_ACA_SistemaBertello.exe


      # El artefacto estarÃ¡ disponible en la pestaÃ±a 'Actions' > 'Run' > 'Artifacts'.
